schemaVersion: 2.2.0
metadata:
  name: kitchensink-ear-eap74-jdk8-devspaces325

components:
  - name: m2
    volume:
      size: 10Gi

  - name: eap-data
    volume:
      size: 5Gi

  # IDE / tooling Dev Spaces 3.25
  - name: development-tooling
    container:
      image: registry.redhat.io/devspaces/udi-rhel9:3.25.0
      memoryLimit: 6Gi
      cpuLimit: 4000m
      env:
        - name: MAVEN_OPTS
          value: "-Dmaven.repo.local=/home/user/.m2/repository"
      volumeMounts:
        - name: m2
          path: /home/user/.m2

  # Build Java 8 (usamos la imagen S2I/builder de EAP 7.4 JDK8)
  - name: build-jdk8
    container:
      image: registry.redhat.io/jboss-eap-7/eap74-openjdk8-openshift-rhel8:7.4.23
      memoryLimit: 6Gi
      cpuLimit: 4000m
      env:
        - name: MAVEN_OPTS
          value: "-Dmaven.repo.local=/home/jboss/.m2/repository"
      volumeMounts:
        - name: m2
          path: /home/jboss/.m2

  # Runtime EAP dentro del workspace: OJO -> usar builder (incluye el servidor)
  - name: eap
    container:
      image: registry.redhat.io/jboss-eap-7/eap74-openjdk8-openshift-rhel8:7.4.23
      memoryLimit: 4Gi
      cpuLimit: 2000m

      # Script de arranque robusto: busca standalone.sh y arranca;
      # si no existe, deja el contenedor vivo para inspección (evita CrashLoop)
      command: ["/bin/bash", "-lc"]
      args:
        - |
          set -euo pipefail
          # heap conservador para evitar OOM en workspaces
          export JAVA_OPTS="${JAVA_OPTS:-}-Xms256m -Xmx1024m -Djava.net.preferIPv4Stack=true"

          for CAND in \
            /opt/eap/bin/standalone.sh \
            /opt/jboss/eap/bin/standalone.sh \
            /opt/jboss/container/jboss-eap/bin/standalone.sh
          do
            if [ -x "$CAND" ]; then
              echo "Starting EAP using: $CAND"
              exec "$CAND" -b 0.0.0.0 -bmanagement 0.0.0.0
            fi
          done

          echo "ERROR: standalone.sh not found in known locations."
          echo "This typically happens when using a *runtime/intermediate* image that does not include the server."
          echo "Use the S2I/builder image: jboss-eap-7/eap74-openjdk8-openshift-rhel8"
          sleep infinity

      volumeMounts:
        # directorios que EAP escribe; además en estas imágenes deployments suele linkear a /deployments
        - name: eap-data
          path: /opt/eap/standalone/tmp
        - name: eap-data
          path: /opt/eap/standalone/data
        - name: eap-data
          path: /opt/eap/standalone/log
        - name: eap-data
          path: /deployments

      endpoints:
        - name: http
          targetPort: 8080
          exposure: public

commands:
  - id: verify-java8
    exec:
      component: build-jdk8
      workingDir: /projects
      commandLine: |
        set -e
        java -version
        mvn -version

  - id: build-ear
    exec:
      component: build-jdk8
      workingDir: /projects
      commandLine: |
        set -e
        mvn -B -DskipTests -pl ear -am clean package
        ls -la ear/target || true

  - id: deploy-ear
    exec:
      component: eap
      workingDir: /projects
      commandLine: |
        set -euo pipefail
        EAR="$(ls -1 ear/target/*.ear | head -n 1)"
        echo "Deploying: $EAR"

        if [ -d /deployments ]; then
          DEPLOY_DIR=/deployments
        else
          DEPLOY_DIR="${JBOSS_HOME:-/opt/eap}/standalone/deployments"
        fi

        cp -f "$EAR" "${DEPLOY_DIR}/kitchensink.ear"
        touch "${DEPLOY_DIR}/kitchensink.ear.dodeploy"
        echo "Done."

  - id: tail-eap-log
    exec:
      component: eap
      workingDir: /projects
      commandLine: |
        set -e
        LOG="${JBOSS_HOME:-/opt/eap}/standalone/log/server.log"
        echo "Tailing: $LOG"
        tail -n 200 -f "$LOG"
